### ISSUE TITLE
Add more css customisation options form semantic-ui

### ISSUE THREAD

**Issue by hugoruscitti** [adfinis-sygroup/ember-validated-form#25]
Hi!, i want to use semantic-ui with this addon, but i have some issues with a lack of some
css customisation options.

For example, i need a css customisation option to set a class name to the form element, and
wrap the field input to show errors.

I make a change in templates to tests this changes, but i wish to find another way to prevent a fork:

https://github.com/hugoruscitti/ember-validated-form/commit/208ca230e53851bf414d33b056b27e5a26144328

any advice ?

**Comment by czosel** [comment]
Hi @hugoruscitti!

Thank you for your feedback! Proper support for semantic-ui is definitely something we'd like to achieve.
After playing around with this for a while, it turns out that some of your changes can already achieved by using the right config properties:
* setting `group: 'field'` will add the `field` class to the `div` wrapping input fields
* setting `help: 'ui red'` will change the class of the `span` containing validation messages
* support for customizable button classes has been added in v0.2.0 (`button: 'ui button'`)

However, some of your requirements needed changes to the codebase: see [this PR](https://github.com/adfinis-sygroup/ember-validated-form/pull/26) and specifically the [updated docs](https://github.com/czosel/ember-validated-form/blob/9ccfbc85c59945a385238d11a5df6c3a829a98fb/README.md#config) which explain the CSS config in more detail and also contain a section on semantic ui.

After the PR went through internal review i'll merge it and publish a new version. If you find the time to look at or test the changes before that any feedback would be greatly appreciated!

**Comment by czosel** [comment]
We just released v0.3.1 including the changes i mentioned above - looking forward to your feedback!

**Comment by hugoruscitti** [comment]
Wow, thanks a lot !!!

**Comment by hugoruscitti** [comment]
I update my application to use this new version and everything works great !!!

thanks @czosel !!

**Comment by czosel** [comment]
Awesome, glad to hear that!
