### ISSUE TITLE
retrieving field value before form is validated

### ISSUE THREAD

**Issue by introvert** [adfinis-sygroup/ember-validated-form#36]
Hello,

Thanks for this lovely plugin.  However, we are facing a major issue which is holding us back. I have a form where I need to observe a field within a form (quantity) and update a field total price as the field is changed.

How to access the value before the form is validated? 

Thanks

**Comment by czosel** [comment]
Hi @introvert, thanks for your nice feedback! :smile: 
Did you already try using the `on-update` option on your input field? This basically makes it one-way-bound.

**Comment by introvert** [comment]
Hey @czosel,

Thanks for your quick reply! I did - it changes to the one-way bound as you said, but it doesn't update the field as its supposed to. Do you maybe have any working examples?

Much appreciated.

**Comment by czosel** [comment]
Since the field is one-way-bound, you'll have to update it manually.  See [this twiddle](https://ember-twiddle.com/7693dda4ebdebcda2065c0b3087011c5?openFiles=templates.application.hbs%2C) for an example. Let me know if that helped, and feel free to tweak the twiddle a bit to illustrate your issue better if it didn't! :smiley:

**Comment by introvert** [comment]
Awesome @czosel.
Thanks a lot for this!

**Comment by czosel** [comment]
You're welcome @introvert! I'll close this - feel free to open a new issue anytime you have another question or a bug to report!
