### ISSUE TITLE
Div tag getting attached to every f.input

### ISSUE THREAD

**Issue by g8anusha** [adfinis-sygroup/ember-validated-form#44]
Hi,
I am using validated-form for validating my page. I see that for every f.input tag, I get a div attached to it. which disturbs my css.

Is there any way in which I can remove the div tags?

**Comment by czosel** [comment]
Hi @g8anusha,

Thanks for your bug report! Unfortunately, there is currently no way to strip the `div` tags from the output. We decided to go with this structure because major CSS frameworks like Bootstrap organize their forms that way - and probably it's also semantically cleaner to group related elements in a div.

Did you try a CSS-only way to approach your issue? If you could post an example of what you're trying to achieve I might be able to give some concrete advice.

**Comment by g8anusha** [comment]
Hey, thanks for the response @czosel !!

I can give you a sample code of what I am doing, bcoz I am not permitted to share my company's code.! :)
What I actually did : 

 <div class="class2">
       {{f.input name="obj1" value=obj class="class3"}}
   </div>

What got rendered : 

<div class="class1">
   <div class="class2">
       {{f.input name="obj1" value=obj class="class3"}}
   </div>
</div>

In the above code, the uppermost div with class as 'class1' got rendered by itself because of using f.input. Because of this, the expected view is being changed, and I am unable to find ways in CSS too to rectify this. I tried a lot of things already.

**Comment by czosel** [comment]
Hi @g8anusha,

thanks for sharing the example code - that definitely helps! 

Did you already try setting the class for the outer div in the config?
```javascript
// environment.js

var ENV = {
  // ...
  'ember-validated-form': {
    css: {
      group: 'class2'
    }
  },
  // ...
}
```
Like that, you could maybe drop your own `<div class="class2">` and just use `{{f.input}}`?

**Comment by g8anusha** [comment]
Hi @czosel,

Thanks for your response. The div that is created is due to another component that I have wrapped inside f.input. To be more specific, I have wrapped power-select and power-select-multiple within them.

Is there any way in which I can use power-select or any another component without having them inside the f.input, but still validate it?

**Comment by czosel** [comment]
Ah, I understand. Currently, we don't have direct support for this. What I did realize after playing around with your use-case a little is that specifying `tagName=""` as an option for your power-select-multiple strips the power-selects containing `div` (see [twiddle](https://ember-twiddle.com/3547207b06ed896f123332dd772503d0?openFiles=templates.application.hbs%2C))

**Comment by g8anusha** [comment]
Hi, I applied the css property in the environment.js, which is great now! But, there are other components that I am using, not only power-select and power-select-multiple. It gets applied for all of them.

Also, tagName="" isn't working with power-select & power-select-multiple. By any chance is it deprecated? I am using ember version 2.10.0!!

**Comment by czosel** [comment]
Dropping the wrapping DOM element is unfortunately not possible at the moment (rendering the input as a tagless component with `tagName=""` throws an error because we're using `classNameBindings` - I don't know how one would avoid that issue). What you can do though is override the element type, for example with `tagName="span"` or whatever else you'd like - I'm not sure if that would help in your case.

Setting `tagName=""` on power-select-multiple seems to work with ember 2.12 in the twiddle i linked above. I'm not sure how stable tagless components are in general though - i didn't find any official information about them in the ember docs (see [here](https://emberjs.com/api/classes/Ember.Component.html#toc_html-tag).

**Comment by czosel** [comment]
I'll close this for now - feel free to reopen the issue if you found something new!
