### ISSUE TITLE
Update an already existing model using validated-form

### ISSUE THREAD

**Issue by g8anusha** [adfinis-sygroup/ember-validated-form#50]
Hi @czosel & Others,

I am getting the model thro the route's model hook. I want to validate an already filled form, retrieved from the server. And, save it using the validated-form.

I made an effort to do it, but what happens is, even if a model is present, validated-form is creating a new empty object for it. So, the changes aren't reflecting in the actual model.

Is there a solution to achieve what I am trying?

Please check this [Twiddle](https://ember-twiddle.com/d7b97d2d23e162ca2ee0344fd7105a15?openFiles=controllers.application.js%2C)

Many thanks in advance!

**Comment by czosel** [comment]
Hi @g8anusha,

our addon relies on [ember-changeset](https://github.com/DockYard/ember-changeset) and [ember-changeset-validations](https://github.com/DockYard/ember-changeset-validations). The basic idea behind these addons is to decouple the form state from your model, following the principle that only validated data should be in the store. That's why you'll have to call `save` on your changeset in order to reflect the recorded changes inside your actual model - please see this [twiddle](https://ember-twiddle.com/3691a8576c35ff149bfc26a564ec5437?openFiles=templates.application.hbs%2C), where I've also added some debug output.

I'd definitely recommend to check out the docs of ember-changeset, they explain the idea behind the approach and the many possibilities you have with them much better than I could :wink:

**Comment by g8anusha** [comment]
Works like magic! Thank you !!! @czosel :100:

**Comment by g8anusha** [comment]
Hi @czosel,

I am trying to have more than one validated-form in the page, for the same model.
Different fields will be applicable for each form. But certain fields in one form, is a computed property of another form (the computed property is given in the model itself, so when we save / get, field is computed and received). 

Since they are different forms, and each form creates a new model, the model is not updating the other form. Is there any way in which this can be achieved? 

Please find this [Twiddle](https://ember-twiddle.com/b9f8fea705f4afbd5e4622040e7efc17?openFiles=templates.application.hbs%2C) for a similar demo.

Many thanks in advance!

**Comment by g8anusha** [comment]
This is an issue with only power-select-multiple component within the validated-form component!
In an already existing form, if only one value is modified and saved & if power-select-multiples are not changed, they disappear during save. Else, the value persists! This occurs only when validated-form is used!! 

Any idea ? :(

**Comment by g8anusha** [comment]
Before model.save, the changes have all the field's value. When model.save is called, only the actually changed values are there. So, this cleans up the actual Ember Data model, and makes the other fields as empty.!!

**Comment by czosel** [comment]
Hi @g8anusha, sorry about the late reply. Did you already make some progress on this issue? You mentioned that the issue only occurs in combination with power-select-multiple - could you try creating a twiddle that shows your exact issue? (You can add addons in twiddle.json)

**Comment by czosel** [comment]
I'll close this for now - feel free to reopen the issue if necessary!
