### ISSUE TITLE
Autofocus on didRender

### ISSUE THREAD

**Issue by willviles** [adfinis-sygroup/ember-validated-form#84]
Currently, input autofocus only occurs on the DOM ready event.

Adding something like the following to `validated-form` would ensure every time the form is rendered, autofocus is respected.

```js
didRender() {
  this._super(...arguments);
  this.focusOnRender();
},

focusOnRender() {
  let $focusInput = this.$().find('[autofocus]');
  if ($focusInput.length) { $focusInput.focus(); }
}
```

Can submit a PR. Also happy to implement in vanilla JS code to comply with future PR https://github.com/emberjs/rfcs/pull/294.

**Comment by czosel** [comment]
Hi @willviles,
Thanks for opening an issue about this! I'm not sure if this is a good idea though, because
* we don't want to make assumptions about what else is going on in the view - maybe there's another component trying to get focus?
* how would you handle the case where there are two validated-form components on the same page?
Maybe it would make more sense use something like [ember-auto-focus](https://github.com/zestia/ember-auto-focus) instead?

**Comment by willviles** [comment]
@czosel I agree. I like the idea of a router plugin, however that doesn't handle cases where forms are rendered conditionally inside routes, which is a requirement of mine.

Ember Auto Focus seems like the best way to implement programmatic autofocus. Thanks for bringing it to my attention!

**Comment by czosel** [comment]
You're welcome! If you learn something about the integration of ember-auto-focus with validated-form that could help others, let me know! Maybe we could add a little section with an example in the README.

**Comment by makepanic** [comment]
One issue of autofocus is that once the user changes focus without changing anything, think of a modal with a form and the user wants to close it, the form validation will be triggered because focusOut triggers `setDirty`.

I'm unsure if we can make focusOut more clever to don't dirty if nothing changes.
