### ISSUE TITLE
Unneeded runtime dependencies

### ISSUE THREAD

**Issue by bendemboski** [adfinis-sygroup/ember-validated-form#86]
The following runtime dependencies are not, as far as I can tell, actually needed at runtime:

* `bower`
* `ember-changeset`
* `ember-changeset-validations`

I think `bower` can just be removed entirely.

The addon is built to use `ember-changeset` and `ember-changeset-validations`, but is usable without them, so putting them in the runtime dependencies makes the addon less lightweight, and requires maintenance to keep up with the latest version (e.g. #69).

I propose that we move them from `dependencies` to `devDependencies` and then either:

1. Add info to the documentation about installing them
2. Install them into apps via a blueprint

I guess this would require a major version bump as it would be a breaking change to anybody using `ember-changeset` or `ember-changeset-validations` that hasn't put them in their own `package.json`.

Thoughts? I'm happy to open a PR removing `bower` and implementing either of the options above.

**Comment by czosel** [comment]
Hi @bendemboski, thanks for bringing this up! I just discussed it with my colleague, and we'd agree to splitting out `ember-changeset` and `ember-changeset-validations` and installing them via a blueprint.
I guess that bower is still needed for running tests, so instead of dropping it completely we could move it to `devDependencies`.
We're looking forward to your PR!

**Comment by czosel** [comment]
Closed in v1.0.0
